1.1.4
denoland/setup-deno pull request #57
Opened 2024-01-28 12:18 UTC by kt3k

This release includes the upgrade of Node.js #56 

I tested the current main HEAD in my project (https://github.com/kt3k/deno_license_checker/pull/35) and it seemed working.

2024-01-28 15:20 UTC, LitoMore commented
@kt3k You may need to run `npm i` again to update the version number in lockfiles.

It is related to https://github.com/denoland/setup-deno/pull/58.

Feel free to close my PR if you want to update the version number in this PR.

2024-01-28 15:21 UTC, LitoMore requested changes
@kt3k You may need to run `npm i` again to update the version number in lockfiles.

It is related to #58.

Feel free to close my PR if you want to update the version number in this PR.

2024-01-28 15:35 UTC, kt3k commented
@LitoMore Thanks. Updated the lockfile.

2024-01-28 16:09 UTC, LitoMore approved these changes

2024-01-28 17:06 UTC, uncenter commented
Wouldn't this be a breaking change? So v2.0.0 instead of v1.1.4?

2024-01-28 17:09 UTC, LitoMore commented
> Wouldn't this be a breaking change? So v2.0.0 instead of v1.1.4? Seems like most other actions consider Node.js upgrades as breaking, from what I've seen. @uncenter

Nope. Our action users can't use its Node.js runtime to run their scripts. So this is not breaking change.

2024-01-28 17:14 UTC, uncenter commented
Ah, true! I forgot this was a Deno repository for a second. 🤦

2024-01-28 21:45 UTC, bartlomieju approved these changes

2024-01-29 04:20 UTC, merged

2024-01-29 04:23 UTC, kt3k commented
Published 1.1.4 https://github.com/denoland/setup-deno/releases/tag/v1.1.4